[package]
name = "sappho-syntax-idstore"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
chumsky.workspace = true
sappho-syntax-identifier.workspace = true
sappho-syntax-parsable.workspace = true
sappho-syntax-unparse.workspace = true

[dev-dependencies]
test-case.workspace = true
