[workspace]
resolver = "2"
members = [
  "attrs",
#   "cli",
  "continuation",
  "east",
  "effect",
  "eval",
  "identifier",
#   "integration-tests",
#   "interpreter",
  "kast",
  "keyword",
  "list",
  "listform",
  "object",
  "parsable",
  "pattern",
  "primval",
  "regression-vectors",
  "source",
  "syntax",
  "tfi",
  "unparse",
  "value",
  "with-source",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "gplv3"
homepage = "https://github.com/nathan-at-least/sappho"

[workspace.dependencies]
aliri_braid = "0.4.0"
anyhow = "1.0.71"
anyhow-std = "0.1.4"
arrayvec = "0.7.6"
chumsky = "0.9.3"
clap = { version = "3.1.18", features = [ "derive", "cargo" ] }
derive-enum-from-into = "0.2.0"
derive_more = { version = "2.0.1", features = [ "full" ] }
derive-new = "0.7.0"
easy-ext = "1.0.2"
either = "1.13.0"
enum_dispatch = "0.3.13"
enum-iterator = "2.1.0"
include_dir = "0.7"
indoc = "1.0.6"
log = "0.4.17"
proc-macro2 = "1.0.94"
quote = "1.0.40"
rand = "0.9.0"
sappho-attrs = { path = "attrs" }
# sappho-cli = { path = "cli" }
sappho-continuation = { path = "continuation" }
sappho-east = { path = "east" }
sappho-effect = { path = "effect" }
sappho-eval = { path = "eval" }
sappho-identifier = { path = "identifier" }
# sappho-integration-tests = { path = "integration-tests" }
# sappho-interpreter = { path = "interpreter" }
sappho-kast = { path = "kast" }
sappho-keyword = { path = "keyword" }
sappho-list = { path = "list" }
sappho-listform = { path = "listform" }
sappho-object = { path = "object" }
sappho-parsable = { path = "parsable" }
sappho-pattern = { path = "pattern" }
sappho-primval = { path = "primval" }
sappho-regression-vectors = { path = "regression-vectors" }
sappho-source = { path = "source" }
sappho-syntax = { path = "syntax" }
sappho-tfi = { path = "tfi" }
sappho-unparse = { path = "unparse" }
sappho-value = { path = "value" }
sappho-with-source = { path = "with-source" }
simplelog = "0.12.0"
syn = "2.0.100"
test-case = "2.0"
thiserror = "2.0.11"
