[package]
name = "sappho-attrs"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive_more.workspace = true
thiserror.workspace = true
sappho-identifier.workspace = true
