[package]
name = "sappho-object"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive-new.workspace = true
sappho-attrs.workspace = true
sappho-unparse.workspace = true
