[package]
name = "sappho-object"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
chumsky.workspace = true
derive-new.workspace = true
derive_more.workspace = true
sappho-attrs.workspace = true
sappho-identifier.workspace = true
sappho-parsable.workspace = true
sappho-tfi.workspace = true
sappho-unparse.workspace = true
sappho-effect.workspace = true
