[package]
name = "sappho-scope"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive-new.workspace = true
sappho-attrs.workspace = true
sappho-listform.workspace = true
sappho-list.workspace = true
sappho-pattern.workspace = true
sappho-primval.workspace = true
sappho-value.workspace = true
thiserror.workspace = true
