[package]
name = "sappho-ast-pattern"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive_more.workspace = true
sappho-attrs.workspace = true
sappho-identifier.workspace = true
sappho-listform.workspace = true
sappho-primval.workspace = true
sappho-unparse.workspace = true
