[package]
name = "sappho-east"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
sappho-identifier.workspace = true
sappho-listform.workspace = true
sappho-object.workspace = true
sappho-primval.workspace = true
sappho-with-source.workspace = true
