[package]
name = "sappho-east"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
sappho-effect.workspace = true
sappho-kast.workspace = true
sappho-parsable.workspace = true
sappho-syntax.workspace = true
sappho-unparse.workspace = true
