[package]
name = "sappho-ast-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive_more.workspace = true
derive-new.workspace = true
sappho-identifier.workspace = true
sappho-primval.workspace = true
sappho-ast-effect.workspace = true
