[package]
name = "sappho-unparse"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive-new.workspace = true
thiserror.workspace = true
