[package]
name = "sappho-listform"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
either.workspace = true
sappho-unparse.workspace = true

[dev-dependencies]
indoc.workspace = true
test-case.workspace = true
