[package]
name = "sappho-syntax-expr"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
chumsky.workspace = true
derive_more.workspace = true
either.workspace = true
sappho-primval.workspace = true
sappho-syntax-idstore.workspace = true
sappho-syntax-parsable.workspace = true
sappho-syntax-unparse.workspace = true
sappho-try-transform.workspace = true

[dev-dependencies]
test-case.workspace = true
