[package]
name = "sappho-rand-dcomp"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive-new.workspace = true
rand.workspace = true
