[package]
name = "sappho-fconv-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
proc-macro = true

[dependencies]
easy-ext.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }

[dev-dependencies]
test-case.workspace = true
indoc.workspace = true
