use rand::distr::Distribution;
use rand::Rng;
use sappho_ast::{ProcEffects, PureEffects, QueryEffects};
use sappho_rand_dcomp::{DistributionExt, WeightedCase};

use crate::AstFuzz;

pub(crate) trait FxFuzz: Sized
where
    AstFuzz: Distribution<Self>,
{
    fn fuzz_weight_factor() -> u32;
}

impl FxFuzz for ProcEffects {
    fn fuzz_weight_factor() -> u32 {
        1
    }
}

impl Distribution<ProcEffects> for AstFuzz {
    fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> ProcEffects {
        self.map(|()| ProcEffects::Inquire)
            .weighted_case(3)
            .or(self.map(|()| ProcEffects::Invoke).weighted_case(1))
            .sample(rng)
    }
}

impl FxFuzz for QueryEffects {
    fn fuzz_weight_factor() -> u32 {
        1
    }
}

impl Distribution<QueryEffects> for AstFuzz {
    fn sample<R: Rng + ?Sized>(&self, _: &mut R) -> QueryEffects {
        QueryEffects::Inquire
    }
}

impl FxFuzz for PureEffects {
    fn fuzz_weight_factor() -> u32 {
        0 // Ensure, at runtime, PureEffects are never generated by fuzzing
    }
}

impl Distribution<PureEffects> for AstFuzz {
    fn sample<R: Rng + ?Sized>(&self, _: &mut R) -> PureEffects {
        unreachable!("PureEffects cannot be sampled")
    }
}
