[package]
name = "sappho-keyword"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
chumsky.workspace = true
enum-iterator.workspace = true
sappho-parsable.workspace = true
sappho-unparse.workspace = true

[dev-dependencies]
test-case.workspace = true
