name: cargo-checkmate phases

on: [workflow_call]
permissions:
  contents: read

jobs:
  cache-checkmate:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-checkmate@0.1.18

  run-phase:
    strategy:
      matrix:
        phase: [audit, build, check, clippy, doc, format, test]
    needs: cache-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-checkmate@0.1.18
      - uses: actions/checkout@v3
      - run: cargo-checkmate run ${{ matrix.phase }}
